### ISSUE TITLE
gather 10 use-cases

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/phylostylotastic#14]
When 5 of us met Oct 3, we decided to each get 2 use-cases, such as a figure from a paper.  The use-case will exemplify the kinds of tree-associated information that needs to be renderable and interoperable.  I created a doc for this here: 

https://github.com/OpenTreeOfLife/phylostylotastic/blob/master/analysis/use_cases1.md

**Comment by nfranz** [comment]
Hi all: Sorry if I don't get all the context. Are weevils an option?

"Broad-noses"
http://taxonbytes.org/pdf/Franz2012-PhylogeneticReassessmentExophthalmus.pdf
(just characters; oh, and Bremer support!! ;o)  )
http://biorxiv.org/content/early/2016/05/17/053611 (biogeography)

"Belids"
https://docs.google.com/document/d/1aGsuqmcrQzPx9Xd2pzwcVmqXIhQoQ9J-bu9Kw_r7K0A/edit?usp=sharing
(host plants..)

Cheers, Nico

**Comment by arlin** [comment]
Nico, the context is that some of us (including Daisie and Jim) are kinda taking over this repo to turn the project into a slightly broader direction.  We want to identify the kinds of information that people add to trees and (1) develop a way to serialize that (i.e., put it in a file according to some standard), (2) decide on conventions for rendering annotations graphically, and then (3) have a hackathon and challenge tree-viz programmers to support this new scheme.  The original Phylostylotastic stylesheets are one way to serialize annotations to be rendered.  

So, your examples are appropriate in the sense that paper 1 has a tree that shows 2 different kinds of support values on internal branches, and it has brackets on clades.  The second tree shows branches annotated with character-state changes.  These are features that are widely used by researchers when they present tree-based visualizations.

**Comment by arlin** [comment]
so, @nfranz,  feel free to add those examples to the use-case doc mentioned above, following the pattern for the first example.

**Comment by jhcepas** [comment]
Some very common features used for species tree visualization:


- Vertical color bands
- Branch length calibration rulers
- node images and silhouttes

http://www.nature.com/nature/journal/v526/n7574/fig_tab/nature15697_F1.html
![image](https://cloud.githubusercontent.com/assets/163658/19475951/e9c39a86-9536-11e6-953f-31334364b5f5.png)
![image](https://cloud.githubusercontent.com/assets/163658/19475961/f4424d72-9536-11e6-8659-eba629d201e3.png)

- Silhouettes
- Node background
- branch length rulers
- Notes on nodes

http://www.nature.com/articles/srep20252/figures/2
![image](https://cloud.githubusercontent.com/assets/163658/19475927/cf37cda4-9536-11e6-9343-6788a25f3ab6.png)


- backgrounds
- vertical bands

http://www.sciencedirect.com/science/article/pii/S1055790313000298#f0005
![image](https://cloud.githubusercontent.com/assets/163658/19475915/c3dc6668-9536-11e6-97fd-d27f59ac7251.png)

- collapsed nodes
- aligned data matrices 
http://www.nature.com/nature/journal/v504/n7479/fig_tab/nature12779_F2.html
![image](https://cloud.githubusercontent.com/assets/163658/19475884/a16d54ac-9536-11e6-868d-94a2e0dd882e.png)



- large trees summarized (e.g. metagenomics)
- circular tree representation
http://www.nytimes.com/interactive/2012/06/19/science/0619-microbiome.html?ref=science&_r=0 
![image](https://cloud.githubusercontent.com/assets/163658/19475876/94d30e94-9536-11e6-91b3-2fb0653d7594.png)

**Comment by arlin** [comment]
@jhcepas, can you put these example in analysis/use_cases1.md?   then we can close this issue.

**Comment by jhcepas** [comment]
@arlin I don't have write access to the repo. Do you want a PR?
