### ISSUE TITLE
NeXML and NEXUS serializations of token data set

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/phylostylotastic#22]
the input files are 
* 2 tree files with different kinds of support value 
* a csv table with tip data
* a csv table with inode data
* metadata files for the csv tables.  

From these, if possible, create a single NeXML file and a single NEXUS file.

**Comment by rvosa** [comment]
As of commit 73d1a872a80c344493f9e456aa03829968294178 there is now a file [annotated.xml](https://github.com/OpenTreeOfLife/phylostylotastic/blob/master/design/viz_targets_exercise/annotated.xml) that contains the tree with all the data embedded as annotations. This is done by a [perl script](https://github.com/OpenTreeOfLife/phylostylotastic/blob/master/design/viz_targets_exercise/convert.pl) whose interface is demonstrated by a [shell script](https://github.com/OpenTreeOfLife/phylostylotastic/blob/master/design/viz_targets_exercise/convert.sh).

**Comment by rvosa** [comment]
Note, by the way, that the predicates that I have used so far are straight from the CSV files. It would be better to pick an appropriate ontology for each of these. For example, the NeXML parser for Mesquite picks up on triples whose predicate is `cdao:has_External_Reference` and whose value is a URL. Those annotations are made clickable.

For other visualization hints we should probably also chat to Bill Piel, because he's been working on visualizing trees using the google maps API and for that he needed NeXML to have annotations (in the 'phylomap' namespace) that stored things like colors, fonts, x/y coordinates, etc.

**Comment by rvosa** [comment]
As of commit 800a12c there is now also a file [remapped.xml](https://github.com/OpenTreeOfLife/phylostylotastic/blob/master/design/viz_targets_exercise/remapped.xml) that applies the suggestions in the previous comment:

- the predicates are remapped as suggested
- `dcterms:license` and `dcterms:rightsHolder` are triples whose subject is the image URL
- the tip data have become character matrices

In addition, I remapped the bootstrap and posterior to the phyloxml namespace and put them as triples whose subject is a 'phyloxml:confidence' annotation. The rationale for this is that Bio::Phylo converts this into the correct phyloxml syntax (which already has slots for support values) when you export this nexml file to phyloxml.

**Comment by rvosa** [comment]
What is still open for debate is whether quite a few of these annotations should actually go to the taxon. I would argue that `dwc:vernacularName`, `dwc:associatedMedia` (i.e. the image, and the rights & ownership statements attached to it) and `cdao:has_External_Reference` are more properly attached to taxa, not tree nodes.

Of course this depends a little bit on how we plan to embed this data in other files. In NEXUS you might do something like:
- put the mass and trophic level data in characters blocks
- put the support values in figtree-style annotations on nodes
- put the taxon annotations in a NOTES block for taxa (YMMV)

But in file formats that don't have this notion of blocks (i.e. Newick flavours, or @jhcepas's tabular format with adjacency columns) it would have to be tunneled some other way. In any case, I suppose that's food for discussion on the next call(s).

**Comment by arlin** [comment]
Is there any reason to continue with the NEXUS strategy?  I'm not just trying to get out of any work (although that's part of it).  I don't know of any tool that parses a NOTES block, unless it's Mesquite.

**Comment by rvosa** [comment]
Erm, yeah, I think only Mesquite can do anything with NOTES blocks. Did I add you on the message to @jhcepas about tabular representations of trees and metadata? I can imagine there's something to discuss there, at least for later today on the call.

**Comment by jhcepas** [comment]
ETE cannot read those blocks. Maybe FigTree?

**Comment by arlin** [comment]
@rvosa, can you present this at the meeting today?  I think we will have our hands full just with the NeXML.  However, I'm about to fire up Mesquite and create as much NEXUS as I can in the next hour.

**Comment by rvosa** [comment]
Yup.

**Comment by arlin** [comment]
I have created a NEXUS serialization in test_data.nex .  

* the three trees (one with bootstraps, one with posteriors) are all in the TREES block
   * but Mesquite seems to strip them out
* links to images (but not license data) are in NOTES
   * but the written NEXUS standard doesn't allow "URL" sources, only allows "file", "inline" and "resource" (meaning Mac resource fork) 
* this does not include any of the internal-node-associated data.  
* this uses the NOTES block for common names and NCBI ids in a way that I thought would be consistent with Mesquite, but which Mesquite does not recognize.  

So, this is a NEXUS file that can't be read by any software that exists, and it still is incomplete.

**Comment by mjy** [comment]
Re:

> So, this is a NEXUS file that can't be read by any software that exists, and it still is incomplete." 

Can this read it  https://github.com/mjy/nexus_parser ? There are pretty good unit tests on that library. 

_Full disclaimer- You should likely ignore this comment.  This is only extremely tangential to this issue, and I've spent zero time remembering if I serialize the notes into a Ruby variable.  _

I am very interested in the semantics behind the image links though-

**Comment by arlin** [comment]
thanks for your interest, @mjy .   The obvious thing to say in NOTES is 

`PICTURE TAXON=1 FORMAT=JPG SOURCE=URL PICTURE=http://media.eol.org/content/2012/06/13/00/48543_orig.jpg;`

But the NEXUS standard only allows SOURCE to be FILE, INLINE and RESOURCE (Mac resource fork).  

We decided to abandon NEXUS as a possible serialization for our data sets, because it just isn't expressive enough.  There is no way to annotate internal nodes, for instance.   

If you want to chat some time, I could quickly explain what we are doing in this project.

**Comment by arlin** [comment]
So, this issue is closed.  we have both serializations as far as we're going to take them.

**Comment by rvosa** [comment]
So what's the homework for next week?

**Comment by arlin** [comment]
you don't have any homework, @rvosa .  The next step is for the people who want to implement the 5 rendering targets in viz_targets_exercise/targets.md .   Jaime is probably going to this with his serialization using ETE.  Daisie is going to use Mesquite and probably NeXML.   Jim and Rick have a TreeIllustrator tool which consumes nexson I think, so they might try to adapt to NeXML.  In any case, these 3 teams will try to implement the rendering targets.  Then we'll evaluate what we've learned.  I think then we would have enough material to write a paper that could serve as inspiration for the hackathon next spring.

**Comment by rvosa** [comment]
I'm going to expand the Bio::Phylo tree drawer :-)

**Comment by mjy** [comment]
@arlin I'm interested in chatting, especially if you have or are setting up unit-test like frameworks for target rendering like you seem to at the start of this issue.  I.e. if I have this data, then your NeXML should look like this.  I suspect we'll be at the point where we are able to do some NeXML rendering in TaxonWorks next year.

**Comment by arlin** [comment]
@mjy, are you available at 3:00 pm eastern today for a 20-minute chat?

**Comment by mjy** [comment]
@arlin Sorry- just saw this now, my gmail filter filed the notification away.  I'm pretty free tomorrow and next week, ping my by email perhaps.

**Comment by arlin** [comment]
let’s just set a time.  Wednesday noon Eastern?  

On Dec 8, 2016, at 10:29 PM, Matt <notifications@github.com> wrote:

> @arlin Sorry- just saw this now, my gmail filter filed the notification away. I'm pretty free tomorrow and next week, ping my by email perhaps.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------
Arlin Stoltzfus (arlin@umd.edu)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.org
